package services

import "github.com/google/wire"

var ProviderSet = wire.NewSet(
	NewIdentityService,
	NewAdminUserService,
	NewAdminProfileService,
	NewAdminProfileMergeService,
	NewAdminGrantService,
	NewAdminCatalogService,
	NewKratosService,
	NewMinecraftService,
	NewAccessService,
	NewProfileService,
	NewProfileCosmeticsService,
	NewSeasonService,
	NewSeasonWorldService,
	NewChunkClaimService,
	NewMojangService,
	NewPlayerSyncService,
	NewRoleSyncService,
	NewProfileResyncService,
	NewProfileVerificationService,
	NewPremiumUUIDService,
	NewProductService,
	NewFulfillmentService,
	NewOrderService,
	NewBasketService,
	NewPurchaseService,
	NewNotificationService,
	NewAnnouncementService,
	NewAccountService,
	NewEasyDonateService,
	NewUploadService,
)
