import 'server-only'
import { headers } from 'next/headers'
import { cache } from 'react'
import type { AdminData } from './types'

export class AdminError extends Error {
  constructor(public status: number, message: string) { super(message) }
}

export async function adminRequest(path: string, options: RequestInit = {}) {
  const service = process.env.ADMIN_SERVICE_URL
  if (!service) throw new AdminError(503, 'Административный сервис не настроен.')
  const incoming = await headers()
  try {
    return await fetch(`${service.replace(/\/$/, '')}${path}`, {
      ...options,
      headers: {
        cookie: incoming.get('cookie') ?? '',
        ...options.headers,
      },
      cache: 'no-store',
      redirect: 'error',
      signal: AbortSignal.timeout(20000),
    })
  } catch {
    throw new AdminError(503, 'Административный сервис недоступен. Повторите позже.')
  }
}

async function readAdmin<T>(path: string): Promise<T> {
  const response = await adminRequest(path)
  const data = await response.json()
  if (!response.ok) throw new AdminError(response.status, data.error ?? 'Не удалось загрузить данные.')
  return data as T
}
export const adminSession = cache(() => readAdmin<{ actor: string }>('/session'))
export const adminData = (path: string) => readAdmin<AdminData>(path)

export function adminURL(base: string, path: string) {
  // Service links are relative paths generated by the admin service.
  return `${base}${path === '/' ? '' : path}`
}

export function queryString(values: Record<string, string | string[] | undefined>, allowed: string[]) {
  const query = new URLSearchParams()
  for (const key of allowed) {
    const value = values[key]
    if (typeof value === 'string') query.set(key, value)
  }
  return query.toString()
}
