// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/lania-smp/shell/internal/clients"
	"github.com/lania-smp/shell/internal/services"
	"github.com/lania-smp/shell/internal/storage"
	"github.com/lania-smp/shell/internal/transport/rpc"
	"google.golang.org/grpc"
)

import (
	_ "github.com/joho/godotenv/autoload"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context) (*grpc.Server, func(), error) {
	db, cleanup, err := storage.NewDatabase(ctx)
	if err != nil {
		return nil, nil, err
	}
	planStorage := storage.NewPlanStorage(db)
	flectoneStorage := storage.NewFlectoneStorage(db)
	playerService := services.NewPlayerService(planStorage, flectoneStorage)
	playerHandler := rpc.NewPlayerHandler(playerService)
	luckpermsStorage := storage.NewLuckpermsStorage(db)
	console := clients.NewConsole()
	permissionService := services.NewPermissionService(luckpermsStorage, console)
	permissionHandler := rpc.NewPermissionHandler(permissionService)
	whitelistService := services.NewWhitelistService(console)
	whitelistHandler := rpc.NewWhitelistHandler(whitelistService)
	server := rpc.NewServer(playerHandler, permissionHandler, whitelistHandler)
	return server, func() {
		cleanup()
	}, nil
}
