// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/lania-smp/backend/internal/api"
	"github.com/lania-smp/backend/internal/clients"
	"github.com/lania-smp/backend/internal/handlers"
	"github.com/lania-smp/backend/internal/services"
	"github.com/lania-smp/backend/internal/storage"
)

import (
	_ "github.com/joho/godotenv/autoload"
	_ "github.com/lania-smp/backend/docs"
)

// Injectors from wire.go:

func InitializeAPI(ctx context.Context) (api.LaniaAPI, func(), error) {
	mainStorage, cleanup, err := storage.NewMainStorage(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacheStorage, err := storage.NewCacheStorage(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	statusHandler := handlers.NewStatusHandler(mainStorage, cacheStorage)
	profileCosmeticsService := services.NewProfileCosmeticsService(mainStorage)
	seasonService := services.NewSeasonService(mainStorage, cacheStorage)
	shellPool, cleanup2, err := clients.NewShellPool(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	minecraftService := services.NewMinecraftService(seasonService, shellPool)
	mojangService := services.NewMojangService(mainStorage, cacheStorage)
	profileService := services.NewProfileService(mainStorage, profileCosmeticsService, minecraftService, mojangService)
	accessService := services.NewAccessService(mainStorage, minecraftService)
	oryAPI, err := clients.NewOryAPI(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	identityService := services.NewIdentityService(oryAPI)
	basketService := services.NewBasketService(mainStorage)
	productService := services.NewProductService(mainStorage)
	accessHandler := handlers.NewAccessHandler(profileService, accessService, seasonService, identityService, basketService, productService, mojangService, mainStorage)
	profileResyncService := services.NewProfileResyncService(profileService, profileCosmeticsService, accessService, seasonService, minecraftService)
	profileRenameService := services.NewProfileRenameService(mainStorage, mojangService, profileResyncService)
	profileHandler := handlers.NewProfileHandler(profileService, accessService, seasonService, minecraftService, mojangService, profileCosmeticsService, profileRenameService)
	profileCosmeticsHandler := handlers.NewProfileCosmeticsHandler(profileCosmeticsService, profileService, minecraftService, seasonService, mainStorage)
	profileResyncHandler := handlers.NewProfileResyncHandler(profileResyncService)
	profileVerificationService := services.NewProfileVerificationService(mainStorage)
	profileVerificationHandler := handlers.NewProfileVerificationHandler(profileVerificationService)
	profileRenameHandler := handlers.NewProfileRenameHandler(profileRenameService)
	profilePasswordService := services.NewProfilePasswordService(mainStorage, accessService, seasonService, minecraftService)
	profilePasswordHandler := handlers.NewProfilePasswordHandler(profilePasswordService)
	productHandler := handlers.NewProductHandler(productService)
	notificationService := services.NewNotificationService(mainStorage)
	fulfillmentService := services.NewFulfillmentService(accessService, profileCosmeticsService, profileService, notificationService)
	orderService := services.NewOrderService(mainStorage, productService, basketService, fulfillmentService)
	easyDonateService := services.NewEasyDonateService(mainStorage, profileService, orderService, minecraftService)
	purchaseService := services.NewPurchaseService(mainStorage, accessService, profileCosmeticsService)
	orderHandler := handlers.NewOrderHandler(orderService, easyDonateService, productService, seasonService, basketService, purchaseService, mainStorage, oryAPI)
	acquiringHandler := handlers.NewAcquiringHandler(mainStorage, orderService)
	purchaseHandler := handlers.NewPurchaseHandler(profileService, accessService, productService, profileCosmeticsService, purchaseService, seasonService)
	basketHandler := handlers.NewBasketHandler(basketService, seasonService, mainStorage)
	adminUserService := services.NewAdminUserService(oryAPI, profileService)
	adminUserHandler := handlers.NewAdminUserHandler(adminUserService)
	adminProfileService := services.NewAdminProfileService(profileService, adminUserService)
	adminProfileMergeService := services.NewAdminProfileMergeService(mainStorage, profileResyncService, notificationService)
	premiumUUIDService := services.NewPremiumUUIDService(mainStorage, profileResyncService)
	adminProfileHandler := handlers.NewAdminProfileHandler(profileService, adminProfileService, adminProfileMergeService, premiumUUIDService, profileRenameService)
	adminGrantService := services.NewAdminGrantService(mainStorage, profileService, productService, seasonService, fulfillmentService, accessService, profileCosmeticsService, minecraftService, notificationService)
	adminGrantHandler := handlers.NewAdminGrantHandler(adminGrantService)
	adminOrderHandler := handlers.NewAdminOrderHandler(orderService)
	adminCatalogService := services.NewAdminCatalogService(mainStorage)
	objectStorage, err := clients.NewObjectStorage(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	glythPackService := services.NewGlythPackService(mainStorage, objectStorage)
	adminCatalogHandler := handlers.NewAdminCatalogHandler(adminCatalogService, easyDonateService, glythPackService)
	seasonHandler := handlers.NewSeasonHandler(seasonService)
	seasonWorldService := services.NewSeasonWorldService(mainStorage, seasonService)
	seasonWorldHandler := handlers.NewSeasonWorldHandler(seasonWorldService)
	chunkClaimService := services.NewChunkClaimService(mainStorage, seasonService, seasonWorldService, minecraftService)
	chunkClaimHandler := handlers.NewChunkClaimHandler(chunkClaimService, profileCosmeticsService)
	announcementService := services.NewAnnouncementService(oryAPI, mainStorage)
	notificationHandler := handlers.NewNotificationHandler(notificationService, announcementService)
	accountService := services.NewAccountService(mainStorage, oryAPI, profileService, profileCosmeticsService, profileResyncService)
	accountHandler := handlers.NewAccountHandler(accountService)
	uploadService := services.NewUploadService(objectStorage)
	uploadHandler := handlers.NewUploadHandler(uploadService)
	playerSyncService := services.NewPlayerSyncService(mainStorage, seasonService, minecraftService)
	roleSyncService := services.NewRoleSyncService(mainStorage, minecraftService)
	laniaAPI := api.NewLaniaAPI(statusHandler, accessHandler, profileHandler, profileCosmeticsHandler, profileResyncHandler, profileVerificationHandler, profileRenameHandler, profilePasswordHandler, productHandler, orderHandler, acquiringHandler, purchaseHandler, basketHandler, adminUserHandler, adminProfileHandler, adminGrantHandler, adminOrderHandler, adminCatalogHandler, seasonHandler, seasonWorldHandler, chunkClaimHandler, notificationHandler, accountHandler, uploadHandler, mojangService, playerSyncService, roleSyncService, profileRenameService, oryAPI)
	return laniaAPI, func() {
		cleanup2()
		cleanup()
	}, nil
}
