// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/lania-smp/backend/internal/api"
	"github.com/lania-smp/backend/internal/clients"
	"github.com/lania-smp/backend/internal/handlers"
	"github.com/lania-smp/backend/internal/services"
	"github.com/lania-smp/backend/internal/storage"
)

import (
	_ "github.com/joho/godotenv/autoload"
	_ "github.com/lania-smp/backend/docs"
)

// Injectors from wire.go:

func InitializeAPI(ctx context.Context) (api.LaniaAPI, func(), error) {
	mainStorage, cleanup, err := storage.NewMainStorage(ctx)
	if err != nil {
		return nil, nil, err
	}
	cacheStorage, err := storage.NewCacheStorage(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	statusHandler := handlers.NewStatusHandler(mainStorage, cacheStorage)
	profileCosmeticsService := services.NewProfileCosmeticsService(mainStorage)
	shellAPI, cleanup2, err := clients.NewShellAPI(ctx)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	minecraftService := services.NewMinecraftService(shellAPI)
	profileService := services.NewProfileService(mainStorage, cacheStorage, profileCosmeticsService, minecraftService)
	accessService := services.NewAccessService(mainStorage, minecraftService)
	seasonService := services.NewSeasonService(mainStorage)
	oryAPI, err := clients.NewOryAPI(ctx)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	identityService := services.NewIdentityService(oryAPI)
	basketService := services.NewBasketService(mainStorage)
	productService := services.NewProductService(mainStorage)
	accessHandler := handlers.NewAccessHandler(profileService, accessService, seasonService, identityService, basketService, productService, mainStorage)
	mojangService := services.NewMojangService(mainStorage, cacheStorage)
	profileHandler := handlers.NewProfileHandler(profileService, accessService, minecraftService, mojangService, profileCosmeticsService)
	profileCosmeticsHandler := handlers.NewProfileCosmeticsHandler(profileCosmeticsService, profileService, minecraftService, mainStorage)
	productHandler := handlers.NewProductHandler(productService)
	freekassaService := services.NewFreekassaService(mainStorage)
	orderService := services.NewOrderService(mainStorage, freekassaService, accessService, profileCosmeticsService, productService, basketService, profileService)
	easyDonateService := services.NewEasyDonateService(mainStorage, profileService, orderService)
	purchaseService := services.NewPurchaseService(mainStorage, accessService, profileCosmeticsService)
	orderHandler := handlers.NewOrderHandler(orderService, freekassaService, easyDonateService, productService, basketService, purchaseService, mainStorage, oryAPI)
	acquiringHandler := handlers.NewAcquiringHandler(mainStorage, orderService)
	purchaseHandler := handlers.NewPurchaseHandler(profileService, accessService, productService, profileCosmeticsService, purchaseService)
	basketHandler := handlers.NewBasketHandler(basketService, mainStorage)
	integrationService := services.NewIntegrationService(mainStorage, orderService)
	laniaAPI := api.NewLaniaAPI(statusHandler, accessHandler, profileHandler, profileCosmeticsHandler, productHandler, orderHandler, acquiringHandler, purchaseHandler, basketHandler, integrationService, mojangService, oryAPI)
	return laniaAPI, func() {
		cleanup2()
		cleanup()
	}, nil
}
